version: 2

orbs:
  node: circleci/node4.0.0

version: 2.1

references:
  copy_npmrc: &COPY_NPMRC
    run:
      name: Copy .npmrc
      command: >-
        sudo rm -rf /var/lib/apt/lists/* && 
        sudo apt-get update &&
        sudo apt-get install -y gettext-base &&
        envsubst < .circleci/templates/npmrc > .npmrc

workflows:
  app-tests:
    jobs:
      - checkout
      - *COPY_NPMRC
      - node/test