# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
name: build_and_test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: yarn
      - run: yarn build
      - run: yarn run ci:test